### ISSUE TITLE
I tried downloading the project, but gradle can't download

### ISSUE THREAD

**Issue by hoangchungk53qx1** [AgoraIO-Usecase/Agora-Scenario-Examples#18]
![Screen Shot 2022-11-24 at 14 36 17](https://user-images.githubusercontent.com/52132635/203721443-d966f50b-5352-44bc-b60f-13968af8140f.png)

**Comment by ygren** [comment]
I have the same problem, so  how do you solve it?

**Comment by hoangchungk53qx1** [comment]
I fixed this,change version syncmanager to 2.0.8

**Comment by xgfd3** [comment]
这个问题已经在最新main分支的代码上修复。
